Repository Selecro/Selecro-aplikace, pull requests merged in 2023-04, with the labels that each got.

#62 barva
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  e2e/tsconfig.json
  src/app/pages/vyukovy-mod/detail/detail.page.scss
Labels: enhancement, review requested

#65 JazykovaMutace
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/pages/home/home.module.ts
  src/app/pages/home/home.page.html
  src/app/pages/home/home.page.ts
  src/app/pages/navody/navody.module.ts
  src/app/pages/navody/navody.page.html
  src/app/pages/navody/navody.page.ts
  src/app/pages/navody/vnitrek/detail/detail.module.ts
  src/app/pages/navody/vnitrek/detail/detail.page.html
  src/app/pages/navody/vnitrek/detail/detail.page.ts
  src/app/pages/navody/vnitrek/vnitrek.module.ts
  src/app/pages/navody/vnitrek/vnitrek.page.html
  src/app/pages/navody/vnitrek/vnitrek.page.ts
  src/app/pages/prihlaseni/prihlaseni.module.ts
  src/app/pages/prihlaseni/prihlaseni.page.html
  src/app/pages/slovnik/slovnik.module.ts
  src/app/pages/slovnik/slovnik.page.html
  src/app/pages/slovnik/slovnik.page.ts
  src/app/pages/vyukovy-mod/detail/detail.module.ts
  src/app/pages/vyukovy-mod/detail/detail.page.html
  src/app/pages/vyukovy-mod/detail/detail.page.ts
  src/app/pages/vyukovy-mod/vyukovy-mod.module.ts
  src/app/pages/vyukovy-mod/vyukovy-mod.page.html
  src/app/pages/vyukovy-mod/vyukovy-mod.page.ts
  src/app/services/dictionary.service.ts
  src/app/services/navody.service.ts
  src/app/services/pomucky.service.ts
  src/app/services/vyuka.service.ts
  src/assets/i18n/CZ.json
  src/assets/i18n/EN.json
Labels: enhancement, invalid

#66 Revert "JazykovaMutace"
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/pages/home/home.module.ts
  src/app/pages/home/home.page.html
  src/app/pages/home/home.page.ts
  src/app/pages/navody/navody.module.ts
  src/app/pages/navody/navody.page.html
  src/app/pages/navody/navody.page.ts
  src/app/pages/navody/vnitrek/detail/detail.module.ts
  src/app/pages/navody/vnitrek/detail/detail.page.html
  src/app/pages/navody/vnitrek/detail/detail.page.ts
  src/app/pages/navody/vnitrek/vnitrek.module.ts
  src/app/pages/navody/vnitrek/vnitrek.page.html
  src/app/pages/navody/vnitrek/vnitrek.page.ts
  src/app/pages/prihlaseni/prihlaseni.module.ts
  src/app/pages/prihlaseni/prihlaseni.page.html
  src/app/pages/slovnik/slovnik.module.ts
  src/app/pages/slovnik/slovnik.page.html
  src/app/pages/slovnik/slovnik.page.ts
  src/app/pages/vyukovy-mod/detail/detail.module.ts
  src/app/pages/vyukovy-mod/detail/detail.page.html
  src/app/pages/vyukovy-mod/detail/detail.page.ts
  src/app/pages/vyukovy-mod/vyukovy-mod.module.ts
  src/app/pages/vyukovy-mod/vyukovy-mod.page.html
  src/app/pages/vyukovy-mod/vyukovy-mod.page.ts
  src/app/services/dictionary.service.ts
  src/app/services/navody.service.ts
  src/app/services/pomucky.service.ts
  src/app/services/vyuka.service.ts
  src/assets/i18n/CZ.json
  src/assets/i18n/EN.json
Labels: review requested

#69 fix backend api
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: enhancement, review requested
