Repository Selecro/Selecro-aplikace, pull requests merged in 2023-03, with the labels that each got.

#40 predelani ikon do svg
  src/app/pages/slovnik/slovnik.page.html
  src/assets/icon/book.png
  src/assets/icon/dlouhy-sloupek.png
  src/assets/icon/dlouhy-sloupek.svg
  src/assets/icon/ig.png
  src/assets/icon/info.png
  src/assets/icon/kratky-sloupek.png
  src/assets/icon/kratky-sloupek.svg
  src/assets/icon/magicky-krouzek.png
  src/assets/icon/magicky-krouzek.svg
  src/assets/icon/mail.png
  src/assets/icon/pevne-oko.png
  src/assets/icon/pevne-oko.svg
  src/assets/icon/pin.png
  src/assets/icon/polodlouhy-sloupek.png
  src/assets/icon/polodlouhy-sloupek.svg
  src/assets/icon/retizkove-oko.png
  src/assets/icon/retizkove-oko.svg
  src/assets/icon/rozhackovani.png
  src/assets/icon/rozhackovani.svg
  src/assets/icon/school.png
  src/assets/icon/search.png
  src/assets/icon/shackovani.png
  src/assets/icon/shackovani.svg
  src/assets/icon/style.png
  src/assets/icon/view.png
Labels: enhancement, review requested

#45 Css bunek ve vyukovem modu
  src/app/pages/pomucky/pomucky.page.html
  src/app/pages/pomucky/pomucky.page.scss
  src/app/pages/vyukovy-mod/vyukovy-mod.page.html
  src/app/pages/vyukovy-mod/vyukovy-mod.page.scss
Labels: enhancement, review requested

#44 textcolor, video
  src/app/pages/pomucky/pomucky.page.html
  src/app/pages/pomucky/pomucky.page.scss
Labels: enhancement, review requested

#46 navody css
  src/app/pages/navody/navody.page.html
  src/app/pages/navody/navody.page.scss
Labels: enhancement, review requested

#47 css buttons
  src/app/pages/navody/navody.page.html
  src/app/pages/navody/navody.page.scss
Labels: enhancement, invalid, review requested

#52 Cross-realm object access in Webpack 5
  package-lock.json
  package.json
  src/app/pages/vyukovy-mod/detail/detail.page.ts
  src/global.scss
  tsconfig.json
Labels: dependencies, review requested
